name: version-and-changelog

on:
  - push 
  - workflow_call

jobs:
  version-and-changelog:
    runs-on: [bodega]  # Or ubuntu-latest if not using the Pi
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: -1
          
      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true
          bump_each_commit_patch_pattern: ""
          search_commit_body: true
          enable_prerelease_mode: false
          
      - name: Auto-generate CHANGELOG
        uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: ${{ github.repository }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: 'docs/CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update for v${{ steps.version.outputs.version }}'
          TYPE: 'feat:Features,fix:Bug Fixes,docs:Documentation,refactor:Refactors,perf:Performance Improvements, chore: chores'
          REGENERATE_COUNT: 0
          DEFAULT_SCOPE: 'general'
        
      - name: Git tag and push
        run: |
          git config --global user.email "bodegacatsgc@gmail.com"
          git config --global user.name "BodegaCatsGC"
           if [ -f docs/CHANGELOG.md ]; then
          git add docs/CHANGELOG.md
          git commit -m "docs(CHANGELOG): update for v${{ steps.version.outputs.version }}" || echo "Nothing to commit"
          fi
          git tag v${{ steps.version.outputs.version }}
          git push origin master --tags
